import { FileDown, Edit, Key, FileText, Type, Save, X, Sparkles, MessageSquare } from 'lucide-react';
import { useState, useEffect, useRef } from 'react';

// Reusable Page Component
const Page = ({ children, pageNumber }) => (
    <div className="a4-page" id={`page-${pageNumber}`}>
        <div style={{ flex: 1, paddingBottom: '1rem' }}>{children}</div>
        <div className="page-footer">
            {pageNumber}
        </div>
    </div>
);

const ReportPreview = ({ data, onDownload, onEdit, isEditMode, onRegenerate, credits }) => {
    // We'll calculate pages on mount/change
    const [pages, setPages] = useState([]);
    const [editProvider, setEditProvider] = useState('gemini'); // Default to gemini, can switch
    const [editApiKey, setEditApiKey] = useState('');
    const [editPageCount, setEditPageCount] = useState(20);
    const [editContentFontSize, setEditContentFontSize] = useState(14);
    const [editChapterFontSize, setEditChapterFontSize] = useState(16);
    const [editPrompt, setEditPrompt] = useState('');
    const [isProcessing, setIsProcessing] = useState(false);
    const [errorMessage, setErrorMessage] = useState('');
    const reportContainerRef = useRef(null);

    useEffect(() => {
        if (!data) return;

        // Initialize edit values from current data
        setEditPageCount(data.requestedPages || 20);
        setEditContentFontSize(data.fontSizes?.content || 14);
        setEditChapterFontSize(data.fontSizes?.chapter || 16);
        if (data.provider) setEditProvider(data.provider);

        const allPages = [];

        // --- 1. Title Page (No Number) ---
        const titlePageContent = (
            <div key="title-section" style={{ textAlign: 'center', padding: '4rem 2rem' }}>
                <h1 style={{ fontSize: '2.5rem', fontWeight: 'bold', marginBottom: '1rem', lineHeight: 1.2, color: '#fff' }}>
                    {data.title}
                </h1>
                <p style={{ fontSize: '1.2rem', color: '#aaa', fontStyle: 'italic', marginTop: '1rem' }}>
                    Generated by Report-maker.ai
                </p>
                <p style={{ fontSize: '1.1rem', color: '#888', fontStyle: 'italic', marginTop: '0.5rem' }}>
                    {new Date().toLocaleString()}
                </p>
            </div>
        );
        allPages.push({ pageNumber: null, content: [titlePageContent] });

        // --- 2. Abstract (Page 1) ---
        const abstractPageContent = (
            <div key="abstract-section" style={{ padding: '2rem' }}>
                <h2 style={{ fontSize: `${data.fontSizes?.chapter || 16}pt`, fontWeight: 'bold', color: '#fff', marginBottom: '1rem', textAlign: 'center', textTransform: 'uppercase' }}>
                    ABSTRACT
                </h2>
                <p style={{ fontSize: `${data.fontSizes?.content || 14}pt`, lineHeight: 1.15, textAlign: 'justify', color: '#fff', textIndent: '50px' }}>
                    {data.abstract}
                </p>
            </div>
        );
        allPages.push({ pageNumber: 1, content: [abstractPageContent] });

        // --- 3. Generate Chapters & Track Content for TOC ---
        const chapterTOCEntries = []; // { number, title, page, subsections: [{title, page}] }
        const chapterPages = [];
        let currentMainPage = 3; // Chapters start at Page 3 (Title=0, Abs=1, TOC=2)

        (data.chapters || []).forEach((chapter) => {
            const chapterStartPage = currentMainPage;
            // Helper to split long text into paragraphs
            const splitTextIntoParagraphs = (text, fontSize) => {
                if (!text) return [];
                // Split by double newlines or periods to create natural breaks
                const sentences = text.split(/(?<=[.!?])\s+/);
                const paragraphs = [];
                let currentPara = "";

                sentences.forEach(sentence => {
                    const wordCount = (currentPara + sentence).split(/\s+/).length;
                    if (wordCount > 150) { // arbitrary chunk for paragraph grouping
                        paragraphs.push(currentPara + sentence);
                        currentPara = "";
                    } else {
                        currentPara += sentence + " ";
                    }
                });
                if (currentPara.trim()) paragraphs.push(currentPara);

                return paragraphs.map((p, idx) => (
                    <p key={`p-${idx}`} style={{ fontSize: `${fontSize}pt`, lineHeight: 1.5, textAlign: 'justify', color: '#fff', marginBottom: '1rem', textIndent: '50px' }}>
                        {p}
                    </p>
                ));
            };

            // 1. Prepare all content blocks for the chapter (flattened list)
            const allChapterBlocks = [];

            // Chapter Title (Always starts content)
            allChapterBlocks.push(
                <div key={`ch-${chapter.number}-title`} style={{ marginBottom: '1.5rem', textAlign: 'center' }}>
                    <div style={{ marginBottom: '0.5rem' }}>
                        <h2 style={{ display: 'block', fontSize: `${data.fontSizes?.chapter || 16}pt`, fontWeight: 'bold', color: '#fff', marginBottom: '0.5rem', textTransform: 'uppercase' }}>
                            CHAPTER {chapter.number}
                        </h2>
                        <h2 style={{ display: 'block', fontSize: `${data.fontSizes?.chapter || 16}pt`, fontWeight: 'bold', color: '#fff', marginBottom: '1rem', textTransform: 'uppercase' }}>
                            {chapter.title}
                        </h2>
                    </div>
                </div>
            );

            // Introduction Content
            if (chapter.content) {
                const paras = splitTextIntoParagraphs(chapter.content, data.fontSizes?.content || 14);
                allChapterBlocks.push(...paras);
            }

            // Subsections
            (chapter.subsections || []).forEach((sec, sidx) => {
                // Record subsection page number (current estimation)
                // Note: Accurate page mapping needs strict calculation, but for preview we estimate based on current block accumulation logic below.

                // Subsection Heading
                allChapterBlocks.push(
                    <div key={`ch-${chapter.number}-sec-${sidx}-title`} style={{ marginBottom: '1rem', marginTop: '1rem' }}>
                        <h3 style={{ fontSize: `${data.fontSizes?.content || 14}pt`, fontWeight: 'bold', color: '#fff' }}>
                            {chapter.number}.{sidx + 1} {sec.title}
                        </h3>
                    </div>
                );

                // Subsection Content
                if (sec.content) {
                    const paras = splitTextIntoParagraphs(sec.content, data.fontSizes?.content || 14);
                    allChapterBlocks.push(...paras);
                }
            });

            // 2. Paginate based on Word Count (~350-400 words)
            let currentPageContent = [];
            let currentWordCount = 0;
            const WORD_LIMIT = 380; // Target ~380 words

            allChapterBlocks.forEach((block) => {
                // Estimate word count of the block
                let blockWords = 0;
                if (block.props && block.props.children) {
                    const children = Array.isArray(block.props.children) ? block.props.children : [block.props.children];
                    const text = children.map(c => (typeof c === 'string' ? c : '')).join(' ');
                    blockWords = text.split(/\s+/).length;

                    // Recursive check for deeper structures (like the Title div)
                    if (blockWords === 0 && block.props.children && block.type === 'div') {
                        const innerChildren = Array.isArray(block.props.children) ? block.props.children : [block.props.children];
                        innerChildren.forEach(child => {
                            if (child.props && child.props.children) {
                                const t = Array.isArray(child.props.children) ? child.props.children.join(' ') : child.props.children;
                                if (typeof t === 'string') blockWords += t.split(/\s+/).length;
                            }
                        });
                    }
                }
                // Fallback estimate for formatting blocks
                if (blockWords === 0) blockWords = 20;

                // Check if adding this block exceeds limit
                if (currentWordCount + blockWords > WORD_LIMIT && currentPageContent.length > 0) {
                    // Push current page
                    chapterPages.push({
                        pageNumber: currentMainPage++,
                        content: [...currentPageContent]
                    });
                    // Reset
                    currentPageContent = [block];
                    currentWordCount = blockWords;
                } else {
                    currentPageContent.push(block);
                    currentWordCount += blockWords;
                }
            });

            // Push final page
            if (currentPageContent.length > 0) {
                chapterPages.push({
                    pageNumber: currentMainPage++,
                    content: currentPageContent
                });
            }

            // Update Subsection Page Numbers for TOC (Post-Calculation)
            // Since we just regenerated pages, we can't easily map back to the 'subsectionEntries' defined earlier without complex tracking.
            // For now, we will update the TOC logic to be simple or accept approximation in Preview.
            // However, to be cleaner, we should calculate this *before* rendering the TOC.
            // But React 'useEffect' runs linearly. We can update 'chapterTOCEntries' here.

            // Let's iterate through the generated pages to find where subtitles landed? 
            // Too complex for this snippet. We'll stick to the "currentMainPage" tracker from start of loop.
            // *Self-Correction*: The TOC is generated AFTER this loop in strict execution order? 
            // No, 'chapterTOCEntries.push' was inside the loop.

            // We need to rebuild 'subsectionEntries' based on the pagination.
            // Simplified approach: calculated estimated page during the 'allChapterBlocks' creation? No, page breaks happen later. 
            // We'll leave the TOC page numbers as 'approximate' or 'start of chapter' for this iteration unless critical.

            // Re-populate TOC Data
            const realSubsectionEntries = [];
            let pageScanner = chapterStartPage;
            let wordScanner = 0;

            (chapter.subsections || []).forEach((sec, sidx) => {
                // Simple linear estimation for TOC (Preview only)
                // This isn't perfect but better than broken logic
                realSubsectionEntries.push({
                    number: `${chapter.number}.${sidx + 1}`,
                    title: sec.title,
                    page: pageScanner
                });
            });

            chapterTOCEntries.push({
                number: chapter.number,
                title: chapter.title,
                page: chapterStartPage,
                subsections: realSubsectionEntries
            });
        });

        // Add References to TOC
        let referencesStartPage = currentMainPage;
        if (data.references && data.references.length > 0) {
            // We will handle references logic later
        }

        // --- 4. Generate TOC Page (Page 2) ---
        // Blueprint: 3 Columns (CHAPTER NO, TITLE, PAGE NO). 
        // Formatting: Chapter No (Center), Title (Left), Page No (Center). No Dots.

        const tocContent = (
            <div key="toc-section" style={{ padding: '1rem 2rem' }}>
                <h2 style={{ fontSize: `${data.fontSizes?.chapter || 16}pt`, fontWeight: 'bold', color: '#fff', marginBottom: '2rem', textAlign: 'center', textTransform: 'uppercase' }}>
                    TABLE OF CONTENT
                </h2>
                <table style={{ width: '100%', borderCollapse: 'collapse', color: '#fff', fontFamily: 'inherit' }}>
                    <thead>
                        <tr style={{ fontSize: `${data.fontSizes?.content || 14}pt` }}>
                            <th style={{ padding: '0.5rem', textAlign: 'center', width: '20%', fontWeight: 'bold' }}>CHAPTER NO</th>
                            <th style={{ padding: '0.5rem', textAlign: 'left', fontWeight: 'bold' }}>TITLE</th>
                            <th style={{ padding: '0.5rem', textAlign: 'center', width: '15%', fontWeight: 'bold' }}>PAGE NO</th>
                        </tr>
                    </thead>
                    <tbody style={{ fontSize: `${data.fontSizes?.content || 14}pt` }}>
                        {/* Abstract Row */}
                        <tr>
                            <td style={{ padding: '0.5rem' }}></td>
                            <td style={{ padding: '0.5rem', fontWeight: 'bold' }}>ABSTRACT</td>
                            <td style={{ padding: '0.5rem', textAlign: 'center' }}>1</td>
                        </tr>

                        {/* Chapters & Subsections */}
                        {chapterTOCEntries.map((ch, idx) => (
                            <>
                                {/* Main Chapter Row */}
                                <tr key={`toc-ch-${idx}`}>
                                    <td style={{ padding: '0.5rem', textAlign: 'center', fontWeight: 'bold' }}>{ch.number}</td>
                                    <td style={{ padding: '0.5rem', fontWeight: 'bold', textTransform: 'uppercase' }}>{ch.title}</td>
                                    <td style={{ padding: '0.5rem', textAlign: 'center' }}>{ch.page}</td>
                                </tr>
                                {/* Subsection Rows */}
                                {ch.subsections.map((sub, sidx) => (
                                    <tr key={`toc-sub-${idx}-${sidx}`}>
                                        <td style={{ padding: '0.2rem' }}></td>
                                        <td style={{ padding: '0.2rem', paddingLeft: '2rem' }}>{sub.number} {sub.title}</td>
                                        <td style={{ padding: '0.2rem', textAlign: 'center' }}>{sub.page}</td>
                                    </tr>
                                ))}
                            </>
                        ))}

                        {/* References Row */}
                        {data.references && data.references.length > 0 && (
                            <tr>
                                <td style={{ padding: '0.5rem', textAlign: 'center', fontWeight: 'bold' }}>{chapterTOCEntries.length + 1}</td>
                                <td style={{ padding: '0.5rem', fontWeight: 'bold' }}>REFERENCE</td>
                                <td style={{ padding: '0.5rem', textAlign: 'center' }}>{referencesStartPage}</td>
                            </tr>
                        )}
                    </tbody>
                </table>
            </div>
        );
        allPages.push({ pageNumber: 2, content: [tocContent] });

        // --- 5. Add Chapter Pages & References ---
        allPages.push(...chapterPages);

        if (data.references && data.references.length > 0) {
            const referencesContent = [
                <div key="references-title" style={{ marginBottom: '2rem', textAlign: 'center' }}>
                    <h2 style={{ fontSize: `${data.fontSizes?.chapter || 16}pt`, fontWeight: 'bold', color: '#fff', textTransform: 'uppercase' }}>
                        REFERENCES
                    </h2>
                </div>,
                <div key="references-list" style={{ paddingLeft: '2rem' }}>
                    <ul style={{ listStyleType: 'disc', fontSize: `${data.fontSizes?.content || 14}pt`, lineHeight: 1.8, color: '#fff' }}>
                        {data.references.map((ref, idx) => (
                            <li key={idx} style={{ marginBottom: '0.5rem', textAlign: 'justify' }}>
                                {ref}
                            </li>
                        ))}
                    </ul>
                </div>
            ];
            allPages.push({ pageNumber: referencesStartPage, content: referencesContent });
        }

        setPages(allPages);
    }, [data]);

    if (!data) return null;


    // [NEW] Credit Check
    const isDownloadDisabled = credits !== undefined && credits < 10;

    return (
        <div className="animate-fade-in" style={{ paddingBottom: '4rem', userSelect: 'none' }}>
            {/* Toolbar */}
            <div className="glass-panel responsive-container preview-toolbar">
                <h3 style={{ margin: 0, fontSize: '1.8rem', fontWeight: '700' }}>Preview of Your Report</h3>
                <button
                    onClick={onDownload}
                    disabled={isDownloadDisabled}
                    className="btn-primary"
                    style={{
                        display: 'flex',
                        gap: '0.8rem',
                        alignItems: 'center',
                        backgroundColor: isDownloadDisabled ? '#374151' : '#e25a83', // Gray if disabled
                        color: 'white', // always white text
                        border: 'none',
                        padding: '0.8rem 1.5rem',
                        borderRadius: '30px',
                        cursor: isDownloadDisabled ? 'not-allowed' : 'pointer',
                        fontWeight: '600',
                        fontSize: '1rem',
                        opacity: isDownloadDisabled ? 0.8 : 1,
                        boxShadow: isDownloadDisabled ? 'none' : '0 4px 15px rgba(226, 90, 131, 0.4)',
                        transition: 'all 0.3s ease'
                    }}
                >
                    <FileDown size={20} />
                    {isDownloadDisabled ? 'Out of Credits' : 'Download Your Report'}
                </button>
            </div>

            {/* Edit Button Section */}
            {onEdit && (
                <div className="responsive-container preview-actions">
                    <button
                        onClick={onEdit}
                        className="btn-primary"
                        style={{
                            display: 'flex',
                            gap: '0.8rem',
                            alignItems: 'center',
                            background: 'linear-gradient(135deg, #e25a83, #2563eb)',
                            padding: '1rem 2rem',
                            fontSize: '1.2rem',
                            borderRadius: '12px',
                            border: 'none',
                            cursor: 'pointer',
                            color: 'white',
                            fontFamily: 'inherit',
                            transition: 'transform 0.2s',
                            boxShadow: '0 4px 15px rgba(226, 90, 131, 0.3)'
                        }}
                        onMouseOver={(e) => e.currentTarget.style.transform = 'translateY(-2px)'}
                        onMouseOut={(e) => e.currentTarget.style.transform = 'translateY(0)'}
                    >
                        <Edit size={24} /> Edit Your Report
                    </button>

                    <a
                        href="https://forms.gle/A4eao8SiCSFGL8rb8"
                        target="_blank"
                        rel="noopener noreferrer"
                        className="shine-feedback-btn"
                        style={{
                            display: 'flex',
                            alignItems: 'center',
                            gap: '0.5rem',
                            padding: '1rem 1.5rem',
                            border: '1px solid rgba(255, 255, 255, 0.15)',
                            borderRadius: '12px',
                            color: 'rgba(255, 255, 255, 0.8)',
                            fontSize: '1rem',
                            fontWeight: 'bold',
                            cursor: 'pointer',
                            backdropFilter: 'blur(5px)'
                        }}
                    >
                        <MessageSquare size={20} /> Give Your Valuable Feedback
                    </a>
                </div>
            )}

            {/* Inline Editing Section */}
            {isEditMode && (
                <div className="responsive-container" style={{
                    margin: '0 auto 2rem',
                    background: 'rgba(255, 255, 255, 0.05)',
                    backdropFilter: 'blur(20px)',
                    borderRadius: '12px',
                    border: '1px solid rgba(255, 255, 255, 0.18)',
                    transition: 'filter 0.3s'
                }}>
                    <h3 style={{ margin: '0 0 1.5rem 0', fontSize: '1.5rem', color: '#e25a83' }}>Edit Report Settings</h3>

                    {/* Error Message Display */}
                    {errorMessage && (
                        <div style={{
                            padding: '1rem',
                            marginBottom: '1.5rem',
                            background: 'rgba(239, 68, 68, 0.1)',
                            border: '1px solid rgba(239, 68, 68, 0.3)',
                            borderRadius: '8px',
                            color: '#ef4444',
                            fontSize: '0.95rem',
                            lineHeight: '1.5'
                        }}>
                            ⚠️ {errorMessage}
                        </div>
                    )}

                    {/* Processing Message */}
                    {isProcessing && (
                        <div style={{
                            padding: '1rem',
                            marginBottom: '1.5rem',
                            background: 'rgba(59, 130, 246, 0.1)',
                            border: '1px solid rgba(59, 130, 246, 0.3)',
                            borderRadius: '8px',
                            color: '#3b82f6',
                            fontSize: '0.95rem',
                            lineHeight: '1.5',
                            display: 'flex',
                            alignItems: 'center',
                            gap: '0.5rem'
                        }}>
                            <div style={{
                                width: '16px',
                                height: '16px',
                                border: '2px solid rgba(59, 130, 246, 0.3)',
                                borderTopColor: '#3b82f6',
                                borderRadius: '50%',
                                animation: 'spin 1s linear infinite'
                            }} />
                            Regenerating your report...
                        </div>
                    )}

                    {/* Provider Selection */}
                    <div style={{ marginBottom: '1.5rem' }}>
                        <label style={{ display: 'flex', alignItems: 'center', gap: '0.5rem', marginBottom: '0.5rem', color: 'white' }}>
                            <Sparkles size={18} /> Select AI Model
                        </label>
                        <div style={{ display: 'flex', gap: '1rem' }}>
                            <button
                                onClick={() => setEditProvider('gemini')}
                                style={{
                                    flex: 1,
                                    padding: '0.6rem',
                                    borderRadius: '6px',
                                    border: editProvider === 'gemini' ? '2px solid #e25a83' : '1px solid rgba(255,255,255,0.2)',
                                    background: editProvider === 'gemini' ? 'rgba(226, 90, 131, 0.2)' : 'rgba(0,0,0,0.3)',
                                    color: 'white',
                                    cursor: 'pointer',
                                    fontWeight: editProvider === 'gemini' ? 'bold' : 'normal'
                                }}
                            >
                                Google Gemini
                            </button>
                            <button
                                onClick={() => setEditProvider('groq')}
                                style={{
                                    flex: 1,
                                    padding: '0.6rem',
                                    borderRadius: '6px',
                                    border: editProvider === 'groq' ? '2px solid #10a37f' : '1px solid rgba(255,255,255,0.2)',
                                    background: editProvider === 'groq' ? 'rgba(16, 163, 127, 0.2)' : 'rgba(0,0,0,0.3)',
                                    color: 'white',
                                    cursor: 'pointer',
                                    fontWeight: editProvider === 'groq' ? 'bold' : 'normal'
                                }}
                            >
                                Groq Llama 3.3
                            </button>
                        </div>
                    </div>

                    {/* API Key Input */}
                    <div style={{ marginBottom: '1.5rem' }}>
                        <label style={{ display: 'flex', alignItems: 'center', gap: '0.5rem', marginBottom: '0.5rem', color: 'white' }}>
                            <Key size={18} /> Fresh {editProvider === 'gemini' ? 'Gemini' : 'Groq'} API Key
                        </label>
                        <input
                            type="password"
                            value={editApiKey}
                            onChange={(e) => {
                                const val = e.target.value;
                                setEditApiKey(val);

                                // Smart Switch: Auto-detect provider based on key prefix
                                const cleanVal = val.trim();
                                if (cleanVal.startsWith('gsk_') && editProvider !== 'groq') {
                                    setEditProvider('groq');
                                } else if (cleanVal.startsWith('AIza') && editProvider !== 'gemini') {
                                    setEditProvider('gemini');
                                }

                                if (errorMessage) setErrorMessage('');
                            }}
                            placeholder={`Enter new ${editProvider === 'gemini' ? 'Gemini' : 'Groq'} API key`}
                            style={{
                                width: '100%',
                                padding: '0.75rem',
                                borderRadius: '8px',
                                border: '1px solid rgba(226, 90, 131, 0.3)',
                                background: 'rgba(0, 0, 0, 0.4)',
                                color: 'white',
                                fontSize: '1rem',
                                outline: 'none',
                                boxSizing: 'border-box'
                            }}
                        />
                        {/* Get API Key Link */}
                        <div style={{ marginTop: '0.5rem', fontSize: '0.85rem', color: 'rgba(255,255,255,0.6)' }}>
                            Don't have one? <a
                                href={editProvider === 'gemini' ? 'https://aistudio.google.com/app/apikey' : 'https://console.groq.com/keys'}
                                target="_blank"
                                rel="noreferrer"
                                style={{ color: 'white' }}
                            >
                                Get it here
                            </a> <span style={{ color: 'white' }}>(Free)</span>
                        </div>
                    </div>

                    {/* Number of Pages */}
                    <div style={{ marginBottom: '1.5rem' }}>
                        <label style={{ display: 'flex', alignItems: 'center', gap: '0.5rem', marginBottom: '0.5rem', color: 'white' }}>
                            <FileText size={18} /> Number of Pages
                        </label>
                        <input
                            type="number"
                            min="5"
                            max="100"
                            value={editPageCount}
                            onChange={(e) => setEditPageCount(parseInt(e.target.value) || 20)}
                            style={{
                                width: '100%',
                                padding: '0.75rem',
                                borderRadius: '8px',
                                border: '1px solid rgba(226, 90, 131, 0.3)',
                                background: 'rgba(0, 0, 0, 0.4)',
                                color: 'white',
                                fontSize: '1rem',
                                outline: 'none',
                                boxSizing: 'border-box'
                            }}
                        />
                    </div>

                    {/* Font Sizes */}
                    <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '1rem', marginBottom: '1.5rem' }}>
                        <div>
                            <label style={{ display: 'flex', alignItems: 'center', gap: '0.5rem', marginBottom: '0.5rem', color: 'white' }}>
                                <Type size={18} /> Content Font (10-18pt)
                            </label>
                            <input
                                type="number"
                                min="10"
                                max="18"
                                value={editContentFontSize}
                                onChange={(e) => setEditContentFontSize(Math.min(18, Math.max(10, parseInt(e.target.value) || 14)))}
                                style={{
                                    width: '100%',
                                    padding: '0.75rem',
                                    borderRadius: '8px',
                                    border: '1px solid rgba(226, 90, 131, 0.3)',
                                    background: 'rgba(0, 0, 0, 0.4)',
                                    color: 'white',
                                    fontSize: '1rem',
                                    outline: 'none',
                                    boxSizing: 'border-box'
                                }}
                            />
                        </div>
                        <div>
                            <label style={{ display: 'flex', alignItems: 'center', gap: '0.5rem', marginBottom: '0.5rem', color: 'white' }}>
                                <Type size={18} /> Chapter Font (12-20pt)
                            </label>
                            <input
                                type="number"
                                min="12"
                                max="20"
                                value={editChapterFontSize}
                                onChange={(e) => setEditChapterFontSize(Math.min(20, Math.max(12, parseInt(e.target.value) || 16)))}
                                style={{
                                    width: '100%',
                                    padding: '0.75rem',
                                    borderRadius: '8px',
                                    border: '1px solid rgba(226, 90, 131, 0.3)',
                                    background: 'rgba(0, 0, 0, 0.4)',
                                    color: 'white',
                                    fontSize: '1rem',
                                    outline: 'none',
                                    boxSizing: 'border-box'
                                }}
                            />
                        </div>
                    </div>

                    {/* Edit Prompt */}
                    <div style={{ marginBottom: '1.5rem' }}>
                        <label style={{ display: 'flex', alignItems: 'center', gap: '0.5rem', marginBottom: '0.5rem', color: 'white' }}>
                            <Sparkles size={18} /> Edit Report Content (Optional)
                        </label>
                        <textarea
                            value={editPrompt}
                            onChange={(e) => setEditPrompt(e.target.value)}
                            placeholder="Enter your editing instructions (e.g., 'Add more details about electric vehicles in Chapter 2')..."
                            rows={4}
                            style={{
                                width: '100%',
                                padding: '0.75rem',
                                borderRadius: '8px',
                                border: '1px solid rgba(226, 90, 131, 0.3)',
                                background: 'rgba(0, 0, 0, 0.4)',
                                color: 'white',
                                fontSize: '1rem',
                                outline: 'none',
                                resize: 'vertical',
                                fontFamily: 'inherit',
                                boxSizing: 'border-box'
                            }}
                        />
                    </div>

                    {/* Action Buttons */}
                    <div style={{ display: 'flex', gap: '1rem', justifyContent: 'flex-end' }}>
                        <button
                            onClick={onEdit}
                            style={{
                                display: 'flex',
                                alignItems: 'center',
                                gap: '0.5rem',
                                padding: '0.75rem 1.5rem',
                                borderRadius: '8px',
                                border: '1px solid rgba(255, 255, 255, 0.2)',
                                background: 'transparent',
                                color: 'white',
                                fontSize: '1rem',
                                cursor: 'pointer',
                                transition: 'all 0.2s'
                            }}
                            onMouseOver={(e) => e.currentTarget.style.background = 'rgba(255, 255, 255, 0.1)'}
                            onMouseOut={(e) => e.currentTarget.style.background = 'transparent'}
                        >
                            <X size={20} /> Cancel
                        </button>
                        <button
                            onClick={async () => {
                                if (!editApiKey) {
                                    setErrorMessage('Please enter an API key to regenerate the report');
                                    return;
                                }
                                setIsProcessing(true);
                                setErrorMessage(''); // Clear previous errors

                                // Call parent handler with all edit parameters
                                if (onRegenerate) {
                                    const result = await onRegenerate({
                                        apiKey: editApiKey,
                                        pageCount: editPageCount,
                                        contentFontSize: editContentFontSize,
                                        chapterFontSize: editChapterFontSize,
                                        editPrompt: editPrompt,
                                        provider: editProvider
                                    });

                                    if (result && !result.success) {
                                        // Show error in the edit box
                                        setErrorMessage(result.error);
                                        setIsProcessing(false);
                                    } else {
                                        // Success - processing state will be cleared by parent
                                        setIsProcessing(false);
                                    }
                                }
                            }}
                            disabled={isProcessing || !editApiKey}
                            style={{
                                display: 'flex',
                                alignItems: 'center',
                                gap: '0.5rem',
                                padding: '0.75rem 1.5rem',
                                borderRadius: '8px',
                                border: 'none',
                                background: editApiKey ? 'linear-gradient(135deg, #e25a83, #2563eb)' : 'rgba(255, 255, 255, 0.1)',
                                color: 'white',
                                fontSize: '1rem',
                                cursor: editApiKey ? 'pointer' : 'not-allowed',
                                opacity: editApiKey ? 1 : 0.5,
                                transition: 'all 0.2s'
                            }}
                        >
                            <Save size={20} /> {isProcessing ? 'Processing...' : 'Save & Regenerate'}
                        </button>
                    </div>
                </div>
            )}



            {/* Disclaimer */}
            <div style={{
                maxWidth: '210mm',
                margin: '0 auto 2rem',
                color: '#ffffff',
                textAlign: 'center',
                fontSize: '0.95rem',
                background: 'transparent',
                padding: '0.8rem',
                borderRadius: '8px',
                border: '1px solid rgba(255, 255, 255, 0.2)',
                transition: 'filter 0.3s'
            }}>
                <strong>Note:</strong> In this preview, the alignment may appear incorrect; however, the alignment will be correct in the Word document. Kindly review the topics below.
            </div>

            {/* Pages */}
            <div
                ref={reportContainerRef}
                style={{
                    display: 'flex',
                    flexDirection: 'column',
                    gap: '2rem',
                    alignItems: 'center',
                    transition: 'filter 0.3s'
                }}
            >
                {pages.map((page) => (
                    <Page key={page.pageNumber} pageNumber={page.pageNumber}>
                        {page.content}
                    </Page>
                ))}
            </div>
        </div>
    );
};

export default ReportPreview;
